name: SonarCloud Scan

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    branches:
      - main  # or your default branch

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'  

      - name: Cache SonarCloud tools
        uses: actions/cache@v2
        with:
          path: ~/.sonar
          key: ${{ runner.os }}-sonarcloud-${{ hashFiles('**/*.cs') }}
          restore-keys: |
            ${{ runner.os }}-sonarcloud-

      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          organization: Learnathon
          projectKey: Learnathon-By-Geeky-Solutions/codestormers
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
