name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  sonarscan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          organization: Learnathon-By-Geeky-Solutions
          projectKey: Learnathon-By-Geeky-Solutions/codestormers
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

      # Other steps if needed
